"""locations and computers

Revision ID: 509a4d1a45e8
Revises: 
Create Date: 2026-09-22 13:46:42.192256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '509a4d1a45e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('computers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='установлен', nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('seat_no', sa.Integer(), nullable=True),
    sa.Column('seat_sort', sa.Numeric(), nullable=True),
    sa.Column('temp_note', sa.Text(), nullable=True),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('mac', sa.Text(), nullable=True),
    sa.Column('inv_no', sa.Text(), nullable=True),
    sa.Column('serial', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('os', sa.Text(), nullable=True),
    sa.Column('cpu', sa.Text(), nullable=True),
    sa.Column('ram', sa.Text(), nullable=True),
    sa.Column('drive', sa.Text(), nullable=True),
    sa.Column('gpu', sa.Text(), nullable=True),
    sa.Column('vnc', sa.Text(), nullable=True),
    sa.Column('glpi_id', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computers')
    op.drop_table('locations')
    # ### end Alembic commands ###
